### ISSUE TITLE
Request-example returns illegal JSON

### ISSUE THREAD

**Issue by Natrocx** [sousa-andre/lcu-driver#16]
Running the request example on the /lol-chat/v1/me endpoint returns a string like so:
```
{'availability': 'chat', 'gameName': 'Natrocx', 'gameTag': 'EUW', 'icon': 715, 'id': '04e3da3d-8761-5fc7-819b-e5b85923d940@eu1.pvp.net', 'lastSeenOnlineTimestamp': None, 'lol': {'championId': '', 'companionId': '4008', 'gameQueueType': '', 'gameStatus': 'outOfGame', 'level': '311', 'mapId': '', 'masteryScore': '526', 'puuid': '04e3da3d-8761-5fc7-819b-e5b85923d940', 'rankedLeagueDivision': 'III', 'rankedLeagueQueue': 'RANKED_FLEX_SR', 'rankedLeagueTier': 'GOLD', 'rankedLosses': '0', 'rankedSplitRewardLevel': '2', 'rankedWins': '41', 'regalia': '{"bannerType":2,"crestType":1}', 'skinVariant': '', 'skinname': ''}, 'name': 'Natrocx', 'patchline': 'live', 'pid': '04e3da3d-8761-5fc7-819b-e5b85923d940@eu1.pvp.net', 'platformId': 'EUW1', 'product': 'league_of_legends', 'productName': '', 'puuid': '04e3da3d-8761-5fc7-819b-e5b85923d940', 'statusMessage': '', 'summary': '', 'summonerId': 0000000, 'time': 0}
```

There are multiple things wrong with this. 
1. Putting strings in single quotes is illegal in JSON
2. None is not an expression in JSON

This wouldn't bother me if I wasn't trying to parse this again, which quite frankly doesn't work without a huge hassle.

**Comment by LightshieldDotDev** [comment]
Doesn't it seem weird to you how you see the issue in the endpoint and not in yourself?

**Comment by bangingheads** [comment]
.json() is parsing the response json string into a python dictionary.

1. This is how python dictionaries are printed with single quotes, as single and double quotes are the same
2. None is an expression of python

**Comment by Natrocx** [comment]
It might be somewhat misleading to call the function .json() if it doesn't produce json but that is a different question.

How do I get it to output valid json tho? 
Please excuse me if this is a stupidly easy question but I don't do Python very often.

**Comment by sousa-andre** [comment]
> It might be somewhat misleading to call the function .json() if it doesn't produce json but that is a different question.
> 
> How do I get it to output valid json tho?
> Please excuse me if this is a stupidly easy question but I don't do Python very often.

Use `.text()` instead of `.json()`.

**Comment by Natrocx** [comment]
Thank you for your time; that did indeed help.
