### ISSUE TITLE
connector.close() example

### ISSUE THREAD

**Issue by kurtisdavid** [sousa-andre/lcu-driver#20]
I'm trying out the following example: https://lcu-driver.readthedocs.io/en/latest/examples.html#change-summoner-icon

It updates my summoner-icon but the script immediately ends while the client is still open. Is this expected behavior?

**Comment by sousa-andre** [comment]
That behavior is expected. The library only waits for the client to be closed if you subscibe to at least one websocket event just like [this example](https://lcu-driver.readthedocs.io/en/latest/examples.html#listening-for-summoner-profile-updates). If you believe the library should have a different behavior please let me know.
