### ISSUE TITLE
Please support Http2

### ISSUE THREAD

**Issue by rainzee** [sousa-andre/lcu-driver#22]
Now some LCU API force to use http2. Requests Unable to communicate properly #

**Comment by sousa-andre** [comment]
Which endpoints require http2?

**Comment by rainzee** [comment]
/lol-match-history/v3/matchlist/account/

**Comment by imi4u36d** [comment]
I got 404 response with lcu-driver

**Comment by rainzee** [comment]
Yes, Cause it force use http2. Now python community dosent have a workable http2 lib yet.

**Comment by Dobedoooo** [comment]
I got 404 from ```/lol-match-history/v3/matchlist/account/``` since April 20 even with http2. I use Nodejs.

**Comment by rainzee** [comment]
nodejs work fine

**Comment by zhu659zhu** [comment]
/lol-match-history/v3/matchlist/account/ 
this api works fine now? i got 404
@rainzee

**Comment by rainzee** [comment]
You need to add some header

**Comment by XilyFeAAAA** [comment]
> You need to add some header

I also got 404 invaild function sometimes when i use accept or session.Its strange that i can use it normally on an account, when i switch to another one, the 404 appears. I tried to add header to request,but it doesnt work.I think is it about the account cache?Or when i use some of functions incorrectly, it was blocked?
