### ISSUE TITLE
Dodging lobby

### ISSUE THREAD

**Issue by RoadJDK** [sousa-andre/lcu-driver#23]
response = await connection.request('POST', '/lol-login/v1/session/invoke?destination=lcdsServiceProxy&method=call&args=["","teambuilder-draft","quitV2",""]')

print(await response.json())

returns: 
{'body': {'body': None, 'clientId': 'nil', 'correlationId': '3954134057-197', 'destination': None, 'headers': {}, 'messageId': 'A1C5A6D0-FDCA-7F02-224D-2CDF4B030A25', 'timeToLive': 0.0, 'timestamp': 1654777177421.0}, 'typeName': 'flex.messaging.messages.AcknowledgeMessage'}

instead of dodging the lobby.

The endpoint is correct. I think something is wrong with the library

Any idea?

**Comment by sousa-andre** [comment]
I've to look more into this... The same request is working properly through cURL but is failing when using this library or even Postman (same headers).

**Comment by sousa-andre** [comment]
I'm closing this issue since there was no updates on it and it's not related to the library itself.
