### ISSUE TITLE
Not printing

### ISSUE THREAD

**Issue by UsernameLuxi** [sousa-andre/lcu-driver#25]
Hi there.
I copied one of the examples, but when it is supposed to print summoner displayname etc, nothing is getting printed. The same happens with lockfile.
Am I stupid or did I just miss something?

**Comment by UsernameLuxi** [comment]
the get_summoner_data function is just waiting infinitely, and therefore nothing else is running

**Comment by sousa-andre** [comment]
Can you give more info on this such as your python version, OS (and if you're using vm) and lib version? From what you have said I guess the lib is not finding the Ux process.

**Comment by UsernameLuxi** [comment]
Hi. I reinstalled the module and it worked afterwards. Sorry about that, I'll close the issue.
