### ISSUE TITLE
LCU detects that my client is closing when it is not closed

### ISSUE THREAD

**Issue by feytus** [sousa-andre/lcu-driver#26]
Hello, I recently tried a piece of code that was an example in the library, 
The problem is that when i run the code i get the message that says that the LCU API is ready to be used then i get directly after the message that says that the client has been closed (it is not).
As you can see with the time that is displayed in the output the client opens and closes instantly.

# The code
```python
from random import randint
from datetime import datetime
from lcu_driver import Connector

connector = Connector()


# fired when LCU API is ready to be used
@connector.ready
async def connect(connection):
    print(datetime.now(), 'LCU API is ready to be used.')

# fired when League Client is closed (or disconnected from websocket)
@connector.close
async def disconnect(_):
    print(datetime.now(), 'The client have been closed!')

# starts the connector
connector.start()
```

# Output
```
2022-08-14 15:10:10.715474 LCU API is ready to be used.
2022-08-14 15:10:10.716652 The client have been closed!
```

**Comment by sousa-andre** [comment]
Since you're not subscribing to any websocket event the connector doesn't wait until the client is closed so the function gets called earlier. If you want to wait until the client is closed just subscribe to any ws event by using the `@connector.ws.register` decorator.
