### ISSUE TITLE
[BUG] ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by MissUwuieTime** [sousa-andre/lcu-driver#28]
Hiya! I've encountered an issue that is affecting `lcu-driver`. It seems to have started yesterday and happens occassionally (sometimes it works, sometimes it doesn't). ;w;

**Describe the bug**
`lcu-driver` fails when attempting to start the driver with a `ValueError`.

**To Reproduce**
1. Install the latest version 2.1.3.
2. Install `psutil` 5.6.5.
3. Use minimum reproducible example code below (see Additional Context).
4. Open the League client.
5. Run Python script.
6. Encounter `ValueError` (only if `--riotgamesapi-settings` has an offending line, see Error section).

**Expected behavior**
Expected `lcu-driver` to start without encountering the `ValueError`.

**Error**
```
Traceback (most recent call last):
  File "app.py", line 19, in <module>
    connector.start()
  File "C:\Users\Maevie\Desktop\lcu_driver\env\lib\site-packages\lcu_driver\connector.py", line 53, in start
    wrapper()
  File "C:\Users\Maevie\Desktop\lcu_driver\env\lib\site-packages\lcu_driver\connector.py", line 46, in wrapper
    self.create_connection(connection)
  File "C:\Users\Maevie\Desktop\lcu_driver\env\lib\site-packages\lcu_driver\connector.py", line 25, in create_connection
    connection = Connection(self, process_or_string)
  File "C:\Users\Maevie\Desktop\lcu_driver\env\lib\site-packages\lcu_driver\connection.py", line 37, in __init__
    process_args = parse_cmdline_args(process_or_string.cmdline())
  File "C:\Users\Maevie\Desktop\lcu_driver\env\lib\site-packages\lcu_driver\utils.py", line 10, in parse_cmdline_args
    key, value = cmdline_arg[2:].split('=')
ValueError: too many values to unpack (expected 2)
```
This is the offending line that `cmdline_arg` encounters (shortened for brevity):
```
--riotgamesapi-settings=eyJjbGllbnfQ==
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python version: 3.8.3
 - Library version: 2.1.3

**Additional context**
```python
from lcu_driver import Connector
from lcu_driver.events.responses import WebsocketEventResponse

connector = Connector()

@connector.ready
async def connect(connection):
  print("ready")

@connector.close
async def disconnect(connection):
  print("finished")
  await connector.stop()

@connector.ws.register('/lol-summoner/v1/current-summoner', event_types=('UPDATE',))
async def update(connection, event: WebsocketEventResponse):
  print(event.data)

connector.start()
```

**Comment by Scarl5** [comment]
For me it's happening every single time, I'm guessing they must have changed the API recently, with all the changes to privacy in the soloq and stuff

**Comment by bogglez** [comment]
This is a bug in the command line parser in `utils.py` line 10:

```python
            key, value = cmdline_arg[2:].split('=')
```

should be
```python
            key, value = cmdline_arg[2:].split('=', 1)
```

**Comment by sousa-andre** [comment]
> This is a bug in the command line parser in `utils.py` line 10:
> 
> ```python
>             key, value = cmdline_arg[2:].split('=')
> ```
> 
> should be
> 
> ```python
>             key, value = cmdline_arg[2:].split('=', 1)
> ```

Fixed in #27

**Comment by ChuniMegu** [comment]
this is the bug thats also cuasing poro lobby to not work, right? i dont understand muich about it sadly, but how can i make porolobby work again? :& can any give me a step to step guide:) tyvm! much appreciated

**Comment by sousa-andre** [comment]
> this is the bug thats also cuasing poro lobby to not work, right? i dont understand muich about it sadly, but how can i make porolobby work again? :& can any give me a step to step guide:) tyvm! much appreciated

Running `pip install git+https://github.com/sousa-andre/lcu-driver` should fix your problem. I want to test the library further before I push it into PyPI.

**Comment by sousa-andre** [comment]
I pushed the new version into PyPI and as such I'm closing this issue. Feel free to re-open it if it's needed.
