### ISSUE TITLE
Creating websocket does not work

### ISSUE THREAD

**Issue by myhrmans** [sousa-andre/lcu-driver#30]
Hi, 
Im trying to create a websocket connection but it does not seem to do anything... How do I know if an endpoint has a websocket connection? 

```
@connector.ws.register('/lol-game-client-chat/v1/muted-summoners', event_types=('UPDATE',))
async def muted_summoner(connection, event):
    print(f'The summoner {event.data["displayName"]} was muted.')
```

**Comment by sousa-andre** [comment]
I suggest you subscribe to [every handler](https://lcu-driver.readthedocs.io/en/latest/quickstart.html#url-patterns) by doing 

```python
@connector.ws.register('/')
async def muted_summoner(connection, event):
    print(event.type, event.uri, event.data)
```

and then you can filter which URIs you want to subscribe to

**Comment by myhrmans** [comment]
The specific endpoint was not a ws endpoint.
